### ISSUE TITLE
Dependency on Dancer2::Plugin is not declared

### ISSUE THREAD

**Issue by andk** [manwar/Dancer2-Plugin-Paginator#2]
As per subject. Grep:

http://search.cpan.org/grep?release=Dancer2-Plugin-Paginator-2.0;string=Dancer2::Plugin;n=1;C=0

This leads to fail reports, e.g.:

http://www.cpantesters.org/cpan/report/85456372
http://www.cpantesters.org/cpan/report/85476131

HTH&&Thanks,

**Comment by manwar** [comment]
Thanks @andk 

This has been resolved in v2.02.
